---
title: "project-512"
author: "Wendi Chu"
date: "2023-04-23"
output: html_document
---

```{r}
library(ISLR)
library(gam)
library(tidyverse)
library(caret)
library(dslabs)
library(ggplot2)

```

```{r}
df=read.csv("adult.csv")
dim(df)
head(df)
```

```{r}
summary(df)
```


```{r}
df=df[df["native.country"]=="United-States",]
df=df[df["workclass"]!="?" & df["occupation"]!="?",]
df[df["income"]==">50K",]["income"]=1
df[df["income"]=="<=50K",]["income"]=0
df=df[,!colnames(df) %in% c("fnlwgt","capital.gain","capital.loss","native.country")]
dim(df)
head(df)
```

```{r}
table_education=table(df["education"]) %>% as.data.frame
table_education$education=as.character(table_education$education)

ggplot(table_education, aes(x="", y=Freq, fill=education))+
  geom_bar(width = 1, stat = "identity")+
  coord_polar("y", start=0)+
  ggtitle("Piechart of Education")+
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  axis.text.x=element_blank(),
  panel.border = element_blank(),
  panel.grid=element_blank(),
  axis.ticks = element_blank(),
  plot.title=element_text(size=14, face="bold")
  )

```

```{r}
table_edunum=table(df$education.num,df$income) %>% as.data.frame
colnames(table_edunum)=c("education.num","income","Freq")

ggplot(table_edunum, aes(fill=income, y=Freq, x=education.num)) + 
    geom_bar(position="dodge", stat="identity")
```

```{r}
p <- df %>%
  ggplot( aes(x=hours.per.week, fill=income)) +
    geom_histogram(color="#e9ecef", alpha=0.6, position = 'identity') +
    labs(fill="")
p
```


```{r}
ggplot(df, aes(x=income, y=age, fill=income)) +
  geom_boxplot()
```

```{r}
ggplot(df, aes(x=income, y=education.num, fill=income)) +
  geom_boxplot()

```

```{r}
df1=mutate(df, y = as.numeric(income == "1"))
df1=df1[,!colnames(df1)=="income"]

set.seed(1001)
split=sample(c(TRUE,FALSE),nrow(df1),replace=TRUE,prob=c(0.8,0.2))
train=df1[split,]
test=df1[!split,]
dim(train)
dim(test)
```

```{r}
fit1=glm(y~ education.num, family = "binomial", data = train)
summary(fit1)
```

```{r}
p_hat_logit=predict(fit1, newdata = test, type = "response")
y_hat_logit=factor(ifelse(p_hat_logit > 0.5, "1", "0"))
confusionMatrix(y_hat_logit, factor(test$y))
```

```{r}
fit2=glm(y~ ., family = "binomial", data = train)
summary(fit2)
```

```{r,warning=FALSE}
p_hat_logit=predict(fit2, newdata = test, type = "response")
y_hat_logit=factor(ifelse(p_hat_logit > 0.5, "1", "0"))
confusionMatrix(y_hat_logit, factor(test$y))
```

```{r}
fit3=glm(y~ age+workclass+education.num+occupation+sex+hours.per.week, family = "binomial", data = train)
summary(fit3)
```

```{r}
p_hat_logit=predict(fit3, newdata = test, type = "response")
y_hat_logit=factor(ifelse(p_hat_logit > 0.5, "1", "0"))
confusionMatrix(y_hat_logit, factor(test$y))
```


